"""Repository ports used by application services."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class UnitOfWorkPort(Protocol):
    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class RepositoryPort(UnitOfWorkPort, Protocol):
    """Application-facing persistence contract without ORM types."""

    async def get_ontology(self, ontology_id: str) -> dict[str, Any]: ...
    async def get_active_ontology(self) -> dict[str, Any] | None: ...
    async def list_ontologies(self) -> list[dict[str, Any]]: ...
    async def create_ontology(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_ontology(self, ontology_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...
    async def ontology_definitions(self, ontology_id: str) -> dict[str, list[dict[str, Any]]]: ...
    async def create_definition(self, kind: str, data: dict[str, Any]) -> dict[str, Any]: ...

    async def find_object(self, object_id: str) -> dict[str, Any]: ...
    async def find_object_by_key(self, stable_key: str) -> dict[str, Any] | None: ...
    async def list_objects(self, object_type_code: str | None = None) -> list[dict[str, Any]]: ...
    async def upsert_object(self, data: dict[str, Any]) -> dict[str, Any]: ...

    async def find_source(self, source_id: str) -> dict[str, Any]: ...
    async def upsert_source(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_sources(self) -> list[dict[str, Any]]: ...
    async def find_latest_pipeline(self, pipeline_key: str) -> dict[str, Any] | None: ...
    async def find_pipeline_by_checksum(self, pipeline_key: str, document_checksum: str) -> dict[str, Any] | None: ...
    async def create_pipeline(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_pipeline(self, pipeline_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def find_observation_by_key(self, idempotency_key: str) -> dict[str, Any] | None: ...
    async def get_observation(self, observation_id: str) -> dict[str, Any]: ...
    async def create_observation(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_observation(self, observation_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def create_provenance(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_provenance(self, provenance_id: str) -> dict[str, Any]: ...

    async def get_fact(self, fact_id: str) -> dict[str, Any]: ...
    async def find_fact_by_identity(self, identity_key: str) -> dict[str, Any] | None: ...
    async def create_fact(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def close_fact_transaction(self, fact_id: str, transaction_to: datetime) -> None: ...
    async def list_facts(
        self,
        *,
        subject_id: str | None = None,
        property_code: str | None = None,
        valid_at: datetime | None = None,
        known_at: datetime | None = None,
    ) -> list[dict[str, Any]]: ...

    async def create_relation(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_relation(self, relation_id: str) -> dict[str, Any]: ...
    async def find_relation_by_identity(self, identity_key: str) -> dict[str, Any] | None: ...
    async def list_relations(
        self,
        subject_id: str | None = None,
        relation_type_code: str | None = None,
        valid_at: datetime | None = None,
        known_at: datetime | None = None,
    ) -> list[dict[str, Any]]: ...

    async def create_rule(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def find_rule_by_idempotency(self, idempotency_key: str) -> dict[str, Any] | None: ...
    async def get_rule(self, rule_id: str) -> dict[str, Any]: ...
    async def list_rules(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def active_rules(self, *, valid_at: datetime | None = None, known_at: datetime | None = None) -> list[dict[str, Any]]: ...
    async def update_rule(self, rule_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...
    async def create_rule_test(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def create_rule_relation(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_rule_tests(self, rule_id: str) -> list[dict[str, Any]]: ...
    async def update_rule_test(self, test_id: str, data: dict[str, Any]) -> dict[str, Any]: ...

    async def get_derived(self, derived_id: str) -> dict[str, Any]: ...
    async def find_derived_by_key(self, result_key: str) -> dict[str, Any] | None: ...
    async def create_derived(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_derived(self, derived_id: str, data: dict[str, Any]) -> dict[str, Any]: ...
    async def add_dependency(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def dependencies_from(self, source_kind: str, source_id: str) -> list[dict[str, Any]]: ...
    async def dependencies_to(self, target_kind: str, target_id: str) -> list[dict[str, Any]]: ...
    async def invalidate_derived(self, derived_ids: list[str], reason: str) -> int: ...

    async def create_review(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_review(self, review_id: str) -> dict[str, Any]: ...
    async def list_reviews(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def find_open_review(self, entity_type: str, entity_id: str, reason: str) -> dict[str, Any] | None: ...
    async def update_review(self, review_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...
    async def create_proposal(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def list_proposals(self, status: str | None = None) -> list[dict[str, Any]]: ...
    async def get_proposal(self, proposal_id: str) -> dict[str, Any]: ...
    async def update_proposal(self, proposal_id: str, data: dict[str, Any], expected_version: int | None = None) -> dict[str, Any]: ...

    async def create_change(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def create_audit(self, data: dict[str, Any]) -> dict[str, Any]: ...
    async def explain_provenance(self, provenance_id: str) -> dict[str, Any]: ...
    async def explain_fact(self, fact_id: str) -> dict[str, Any]: ...
